development:
 adapter: mysql
 database: doconnect_development
 username: root
 password: 
 host: localhost

test:
 adapter: mysql
 database: doconnect_test
 username: root
 password: 
 host: localhost

production:
 adapter: mysql
 database: doconnect_production
 username: root
 password: 
 host: localhost
